version: '3'

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
        # condition: service_completed_successfully
    ports:
      - "9000:9000"
    volumes:
      - wp-data:/var/www
    networks:
      - inception
    env_file:
      - ./.env
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
        # condition: service_completed_successfully
    networks:
      - inception
    volumes:
      - wp-data:/var/www/
    env_file:
      - ./.env
    restart: on-failure

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp-data:/var/www/
    restart: on-failure

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/
    env_file:
      - ./.env
    restart: on-failure

  portainer:
      container_name: portainer
      build:
        context: ./requirements/bonus/portainer
        dockerfile: Dockerfile
      ports:
        - "9443:9443"
      networks:
        - inception
      volumes:
        - "/Users/hameur/Documents/inception/data/portainer:/data"
        - "/etc/localtime:/etc/localtime:ro"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      env_file:
        - ./.env
      restart: on-failure

  static:
    container_name: static
    build:
      context: ./requirements/bonus/static
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: on-failure 

networks:
  inception:
    driver: bridge

volumes:
# change volumes path to  /home/login/data
  wp-data:
    driver_opts:
      o: bind
      type: none
      device: /Users/hameur/Documents/inception/data/wordpress

  db-data:
    driver_opts:
      o: bind
      type: none
      device: /Users/hameur/Documents/inception/data/mariadb
