version: '3'

services:

  mariaDb:
    container_name: mariaDb
    build: ./mariaDB
    ports:
      - 3306:3306
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress
    # ports:
    #   -
    restart: always

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge