version: '3'

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB
    ports:
      - 3306:3306
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql 
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wp-data:/var/www
    networks:
      - inception
    env_file:
      - ./.env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    links:
      - wordpress
    networks:
      - inception
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/sites-available/default/
      - ./requirements/nginx/tools/:/etc/nginx/ssl/
      - wp-data:/var/www
    restart: always

networks:
  inception:
    driver: bridge

volumes:

  wp-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
