version: '3'

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB
    ports:
      - 3306:3306
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql 
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wp-data:/var/www
    networks:
      - inception
    env_file:
      - ./.env
    entrypoint: /entrypoint.sh
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    links:
      - wordpress
    networks:
      - inception
    volumes:
      - ng-data:/etc/nginx/ssl/
      - wp-data:/var/www
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
# change volumes path to  /home/login/data
  wp-data:
    driver_opts:
      o: bind
      type: none
      device: /Users/hameur/Desktop/data/wp

  db-data:
    driver_opts:
      o: bind
      type: none
      device: /Users/hameur/Desktop/data/db

  ng-data:
    driver_opts:
      o: bind
      type: none
      device: /Users/hameur/Desktop/data/ng
